---
- hosts: master1.caaa.poc
  collections:
    - kubernetes.core
  tasks:
  - name: install pre-requisites
    pip:
    name:
      - pyyaml
      - kubernetes 
      
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present
  
  - name: Create a pod
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: "utilitypod-1"
          namespace: default
          labels:
            app: galaxy
        spec:
          containers:
          - name: utilitypod
            image: busybox
